name: Deploy
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1

    - run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc --no-deps

    - name: Deploy API Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
